import 'package:supabase_flutter/supabase_flutter.dart';
import '../models/profile_model.dart';
import '../models/product_model.dart';
import '../models/review_model.dart';

class SellerRepository {
  final SupabaseClient _supabase = Supabase.instance.client;

  Future<Profile?> getProfile(String userId) async {
    try {
      final data = await _supabase
          .from('profiles')
          .select()
          .eq('id', userId)
          .single();
      return Profile.fromJson(data);
    } catch (e) {
      // Return null if not found or error
      return null;
    }
  }

  Future<void> updateProfile(Profile profile) async {
    // Exclude ID from update payload usually, but RLS handles check.
    // We send fields we want to update.
    final updates = profile.toJson();
    updates.remove('id'); // ID is primary key
    updates.remove(
      'role',
    ); // Typically role isn't self-editable easily effectively

    await _supabase.from('profiles').update(updates).eq('id', profile.id);
  }

  Future<List<Product>> getSellerProducts(String sellerId) async {
    final data = await _supabase
        .from('products')
        .select()
        .eq('seller_id', sellerId)
        .order('created_at', ascending: false);

    return (data as List).map((e) => Product.fromJson(e)).toList();
  }

  Future<List<Product>> getAllProducts() async {
    final data = await _supabase
        .from('products')
        .select()
        .order('created_at', ascending: false);

    return (data as List).map((e) => Product.fromJson(e)).toList();
  }

  Future<List<Review>> getProductReviews(String productId) async {
    final data = await _supabase
        .from('reviews')
        .select('*, profiles(full_name, avatar_url)')
        .eq('product_id', productId)
        .order('created_at', ascending: false);

    return (data as List).map((e) => Review.fromJson(e)).toList();
  }

  Future<void> updateProduct(Product product) async {
    final updates = product.toJson();
    updates.remove('id');
    updates.remove('seller_id');
    updates.remove('created_at');

    await _supabase.from('products').update(updates).eq('id', product.id);
  }

  Future<void> createProduct(Product product) async {
    final data = product.toJson();
    data.remove(
      'id',
    ); // Generate ID by DB or let Supabase handle if using gen_random_uuid
    data.remove('created_at'); // Let DB handle default

    // If ID is required by model but generated by DB, we might usually send it without ID
    // But Product model has required ID. We can either generate UUID here or ignore it.
    // Ideally we generate UUID here if we want to use it immediately, or let DB do it.
    // Since Product model demands ID, let's assume we generated one or pass a dummy one that gets ignored if we exclude it.

    // Actually, to insert we just need the values.
    // The previous implementation plan suggested removing ID.

    await _supabase.from('products').insert(data);
  }
}
